import { useState } from "react";
import { View, Text, TextInput, TouchableOpacity, ScrollView, ActivityIndicator, Alert, Platform } from "react-native";
import { Stack, useRouter } from "expo-router";
import * as DocumentPicker from "expo-document-picker";
import { fetchWithCookie } from "../src/lib/api";
import { FileText, X, ArrowUp, Paperclip } from "lucide-react-native";
import { useAuth } from "../src/lib/auth";

export default function CreateUpdateScreen() {
    const router = useRouter();
    const { user } = useAuth();
    const [title, setTitle] = useState(""); // Title is auto-generated by AI in unified, but we might want explicit title if using standard route
    // But mobile usually implies "Unified" flow if we want AI. 
    // Let's use standard input for now: Content + Category.
    
    const [content, setContent] = useState("");
    const [category, setCategory] = useState("general");
    const [files, setFiles] = useState<any[]>([]);
    const [loading, setLoading] = useState(false);

    const categories = ["general", "assignments", "notes", "presentations"];

    const pickDocument = async () => {
        try {
            const result = await DocumentPicker.getDocumentAsync({
                type: "*/*",
                copyToCacheDirectory: true,
                multiple: true
            });
            
            if (!result.canceled && result.assets) {
                setFiles(prev => [...prev, ...result.assets]);
            }
        } catch (err) {
            console.log("Picker error", err);
            Alert.alert("Error", "Failed to pick file");
        }
    };

    const removeFile = (index: number) => {
        setFiles(files.filter((_, i) => i !== index));
    };

    const handleSubmit = async () => {
         if (!content.trim() && files.length === 0) {
             Alert.alert("Error", "Please provide content or files");
             return;
         }

         try {
             setLoading(true);
             const formData = new FormData();
             
             // Use the Unified endpoint (AI-powered)
             // We pass the validation category as a hint in the text
             const finalContext = `Category: ${category}\n\n${content}`;
             
             formData.append('contextText', finalContext);
             
             // Append Files
             files.forEach((file) => {
                 formData.append('files', {
                     uri: file.uri,
                     name: file.name,
                     type: file.mimeType || 'application/octet-stream',
                 } as any);
             });

             const res = await fetchWithCookie("/api/updates/unified", {
                 method: 'POST',
                 body: formData,
             });

             if (!res.ok) {
                 const err = await res.json();
                 throw new Error(err.message || "Failed to create update");
             }
             
             Alert.alert("Success", "Update created successfully!");
             router.back();
         } catch (e: any) {
             console.error(e);
             Alert.alert("Error", e.message);
         } finally {
             setLoading(false);
         }
    };

    return (
        <ScrollView className="flex-1 bg-background">
             <Stack.Screen options={{ 
                title: "New Update", 
                presentation: 'modal',
                headerTitleStyle: { color: "#ffffff", fontWeight: 'bold' },
                headerStyle: { backgroundColor: "#0a0a0a" },
                headerShadowVisible: false,
                headerLeft: () => (
                    <TouchableOpacity onPress={() => router.back()}>
                        <Text className="text-red-500 font-bold text-lg">Cancel</Text>
                    </TouchableOpacity>
                )
             }} />
             
             <View className="p-4 space-y-4">
                 <View>
                     <Text className="text-muted-foreground mb-2 font-medium">Content</Text>
                     <TextInput 
                        className="bg-input text-foreground p-4 rounded-xl border border-border h-40 text-base"
                        multiline
                        textAlignVertical="top"
                        placeholder="What's the update about?"
                        placeholderTextColor="#666"
                        value={content}
                        onChangeText={setContent}
                     />
                 </View>

                 <View>
                     <Text className="text-muted-foreground mb-2 font-medium">Category</Text>
                     <ScrollView horizontal showsHorizontalScrollIndicator={false} className="flex-row gap-2">
                         {categories.map(cat => (
                             <TouchableOpacity 
                                key={cat}
                                onPress={() => setCategory(cat)}
                                className={`px-4 py-2 rounded-full border ${category === cat ? 'bg-primary border-primary' : 'bg-secondary border-border'}`}
                             >
                                 <Text className={`capitalize font-medium ${category === cat ? 'text-primary-foreground' : 'text-muted-foreground'}`}>
                                     {cat}
                                 </Text>
                             </TouchableOpacity>
                         ))}
                     </ScrollView>
                 </View>

                 <View>
                     <View className="flex-row justify-between items-center mb-2">
                        <Text className="text-muted-foreground font-medium">Attachments</Text>
                        <TouchableOpacity onPress={pickDocument} className="flex-row items-center">
                            <Paperclip size={16} color="#ef4444" />
                            <Text className="text-primary ml-1 font-bold">Add File</Text>
                        </TouchableOpacity>
                     </View>
                     
                     {files.map((file, index) => (
                         <View key={index} className="flex-row items-center justify-between bg-secondary p-3 rounded-lg mb-2">
                             <View className="flex-row items-center flex-1 mr-2">
                                 <FileText size={20} color="#a3a3a3" />
                                 <Text className="text-foreground ml-2 flex-1" numberOfLines={1}>{file.name}</Text>
                             </View>
                             <TouchableOpacity onPress={() => removeFile(index)}>
                                 <X size={20} color="#666" />
                             </TouchableOpacity>
                         </View>
                     ))}
                 </View>

                 <TouchableOpacity 
                    className={`bg-primary p-4 rounded-xl items-center flex-row justify-center mt-4 ${loading ? 'opacity-70' : ''}`}
                    onPress={handleSubmit}
                    disabled={loading}
                 >
                     {loading ? (
                         <ActivityIndicator color="#000" />
                     ) : (
                         <>
                            <ArrowUp size={20} color="#000" />
                            <Text className="text-primary-foreground font-bold text-lg ml-2">Post Update</Text>
                         </>
                     )}
                 </TouchableOpacity>
             </View>
        </ScrollView>
    );
}
